Include Debian package in release artifacts
ducaale/xh pull request #172
Opened 2021-09-05 15:16 UTC by ducaale

Resolves https://github.com/ducaale/xh/issues/171

2021-09-05 18:31 UTC, blyxxyz requested changes
Lintian is a linter for Debian packages. Here's what it has to say:

```console
$ lintian xh_0.12.0_amd64.deb
E: xh: no-changelog usr/share/doc/xh/changelog.gz (native package)
W: xh: copyright-without-copyright-notice
W: xh: shared-library-lacks-prerequisites usr/bin/xh
W: xh: unknown-field xh_0.12.0_amd64.deb Vcs-Browser
W: xh: unknown-field xh_0.12.0_amd64.deb Vcs-Git
```

> `E: xh: no-changelog usr/share/doc/xh/changelog.gz (native package)`
> `W: xh: copyright-without-copyright-notice`

I think these are covered by the review comments.

> `W: xh: shared-library-lacks-prerequisites usr/bin/xh`

I can't make sense of this. I think it's complaining that the binary is dynamically linked while the package doesn't depend on `libc`. But:
```console
$ file usr/bin/xh
usr/bin/xh: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=cc1900e452326a1d7aeb1d39cd7bc6e99dd6036b, stripped
$ ldd usr/bin/xh
	statically linked
```
The binary works in an Alpine docker container so it's probably fine.

> `W: xh: unknown-field xh_0.12.0_amd64.deb Vcs-Browser`
> `W: xh: unknown-field xh_0.12.0_amd64.deb Vcs-Git`

I don't think these matter.

2021-09-06 16:55 UTC, ducaale commented
>I can't make sense of this. I think it's complaining that the binary is dynamically linked while the package doesn't depend on libc. But:
>```
>$ file usr/bin/xh
>usr/bin/xh: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, >BuildID[sha1]=cc1900e452326a1d7aeb1d39cd7bc6e99dd6036b, stripped
>$ ldd usr/bin/xh
>	statically linked
>```


Hmm, this is what I see when I use the same commands with the last x86_64-unknown-linux-musl binary that was released:

```
$ file /home/ducaale/.local/bin/xh
/home/ducaale/.local/bin/xh: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
$ ldd /home/ducaale/.local/bin/xh
        not a dynamic executable
```

2021-09-06 19:48 UTC, blyxxyz commented on assets/xh
> +This is a temp file to make cargo-deb happy while copying the xhs symlink.
I've filed mmstick/cargo-deb#192 to avoid needing this.

2021-09-06 19:56 UTC, ducaale commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
Do you plan to open an issue for this in cargo-deb?

2021-09-06 20:15 UTC, blyxxyz commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
I opened mmstick/cargo-deb#193.

Until they are merged we can use `cargo install --git https://github.com/blyxxyz/cargo-deb --branch xh-patches cargo-deb`.

2021-09-06 20:27 UTC, blyxxyz commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
I was wrong about `NEWS.gz` and `changelog.gz` being equivalent. The first is for release notes, the second is a more complete changelog.

Lintian would like `changelog.gz` to exist. It looks like it's sometimes generated from a git log. I'm not quite sure how to handle that, but I think it's ok to skip for now. It's something cargo-deb might be able to do automatically at some point if it detects a git repository.

(So this doesn't need further changes.)

2021-09-06 20:30 UTC, blyxxyz commented
Lintian has a new complaint: `W: xh: no-manual-page usr/bin/xhs`

`ln -s xh.1.gz assets/xhs.1.gz` can solve it, if the filename already ends in `.gz` then it won't trigger cargo-deb's auto-compression.

We should also mention `xhs` in the man page itself but that can happen outside this PR, Lintian doesn't care.

2021-09-06 20:44 UTC, ducaale commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
I am a bit curious about the difference between `NEWS.gz` and `changelog.gz`. Do you know of any examples?

2021-09-06 21:00 UTC, blyxxyz commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
One example is `coreutils`.
- `NEWS.gz` is this file: https://github.com/coreutils/coreutils/blob/master/NEWS
- `changelog.gz` might be generated by [`git-dch`](https://manpages.ubuntu.com/manpages/precise/man1/git-dch.1.html) and looks like this: http://sprunge.us/qrfdub

2021-09-06 21:12 UTC, blyxxyz approved these changes
I think this is ready. It's very nice to have it, thank you!

It's missing shell completions for `xhs`, but that's not as simple as a symlink so that can come later.

2021-09-06 21:16 UTC, ducaale commented on Cargo.toml
> +  ["CHANGELOG.md", "usr/share/doc/xh/CHANGELOG", "644"],
Now I see the difference, thanks!

2021-09-06 21:16 UTC, merged